branch-defaults:
  default:
    environment: Mbtify-env
environment-defaults:
  Mbtify-env:
    branch: null
    repository: null
global:
  application_name: mbtify
  default_ec2_keyname: mbtifykey
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
